data_dir: data/mpom
batch_size: 8
epochs: 100
lr: 1e-4
mask_ratio: 0.5
lambda1: 1.0
lambda2: 0.1
hidden_dim: 512
num_heads: 8
num_layers: 12  # num. of DiTBlock
attn_dropout: 0.1
patch_size: 16
channels: 3
log_input_dim: 128
num_ids: 1000
diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
